#!/usr/bin/env bash
# Doctor: environment preflight, optional config, and install hints.
# Usage:
#   doctor.sh [--json] [--ensure] [--install-missing]
#
# AI workflow:
#   1. Run `doctor.sh --ensure --json` before UI work.
#   2. If required tools are missing, run `doctor.sh --ensure --install-missing`.
#   3. Continue only when `ready=true`.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$HERE/lib.sh"

JSON=0
ENSURE=0
INSTALL_MISSING=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --json) JSON=1; shift ;;
        --ensure) ENSURE=1; shift ;;
        --install-missing) INSTALL_MISSING=1; shift ;;
        -h|--help)
            awk '/^set -uo/{exit} /^#!/{next} /^#/ {sub(/^# ?/, ""); print}' "$0"
            exit 0
            ;;
        *) die "unknown argument: $1" ;;
    esac
done

ROOT="$(find_project_root)"
ENV_FILE="$ROOT/.droidlens/env.sh"

tool_path() {
    command -v "$1" 2>/dev/null || true
}

package_manager() {
    if command -v brew >/dev/null 2>&1; then
        echo brew
    elif command -v apt-get >/dev/null 2>&1; then
        echo apt-get
    elif command -v dnf >/dev/null 2>&1; then
        echo dnf
    elif command -v pacman >/dev/null 2>&1; then
        echo pacman
    elif command -v choco >/dev/null 2>&1; then
        echo choco
    elif command -v scoop >/dev/null 2>&1; then
        echo scoop
    else
        echo ""
    fi
}

install_command_for() {
    local tool="$1" pm="$2"
    case "$pm:$tool" in
        brew:adb) echo "brew install --cask android-platform-tools" ;;
        brew:cwebp) echo "brew install webp" ;;
        brew:pngquant) echo "brew install pngquant" ;;
        apt-get:adb) echo "sudo apt-get update && sudo apt-get install -y adb" ;;
        apt-get:cwebp) echo "sudo apt-get update && sudo apt-get install -y webp" ;;
        apt-get:pngquant) echo "sudo apt-get update && sudo apt-get install -y pngquant" ;;
        dnf:adb) echo "sudo dnf install -y android-tools" ;;
        dnf:cwebp) echo "sudo dnf install -y libwebp-tools" ;;
        dnf:pngquant) echo "sudo dnf install -y pngquant" ;;
        pacman:adb) echo "sudo pacman -S --noconfirm android-tools" ;;
        pacman:cwebp) echo "sudo pacman -S --noconfirm libwebp" ;;
        pacman:pngquant) echo "sudo pacman -S --noconfirm pngquant" ;;
        choco:adb) echo "choco install adb -y" ;;
        choco:cwebp) echo "choco install webp -y" ;;
        choco:pngquant) echo "choco install pngquant -y" ;;
        scoop:adb) echo "scoop install adb" ;;
        scoop:cwebp) echo "scoop install main/libwebp" ;;
        scoop:pngquant) echo "scoop install pngquant" ;;
        *) echo "" ;;
    esac
}

maybe_install() {
    local tool="$1" pm cmd
    [[ "$INSTALL_MISSING" == "1" ]] || return 0
    pm="$(package_manager)"
    cmd="$(install_command_for "$tool" "$pm")"
    [[ -n "$cmd" ]] || return 0
    log "install missing tool: $tool via $pm"
    bash -lc "$cmd"
}

infer_android_home() {
    local adb_path="$1"
    local dir
    dir="$(dirname "$adb_path")"
    if [[ "$(basename "$dir")" == "platform-tools" ]]; then
        dirname "$dir"
    fi
}

write_env_file() {
    local adb_path="$1" serial="$2" android_home="$3"
    [[ "$ENSURE" == "1" ]] || return 0
    mkdir -p "$(dirname "$ENV_FILE")"
    {
        printf '# Generated by scripts/droidlens/doctor.sh --ensure.\n'
        printf '# Values use := so explicit shell env always wins.\n'
        [[ -n "$adb_path" ]] && printf '%s\n' ": \"\${DROIDLENS_ADB:=$adb_path}\""
        [[ -n "$android_home" ]] && printf '%s\n' ": \"\${ANDROID_HOME:=$android_home}\""
        [[ -n "$serial" ]] && printf '%s\n' ": \"\${DROIDLENS_SERIAL:=$serial}\""
        printf '%s\n' ": \"\${DROIDLENS_APP:=auto}\""
    } > "$ENV_FILE"
}

for tool in adb cwebp pngquant; do
    case "$tool" in
        adb) adb_bin >/dev/null 2>&1 || maybe_install adb ;;
        cwebp) command -v cwebp >/dev/null 2>&1 || maybe_install cwebp ;;
        pngquant) command -v pngquant >/dev/null 2>&1 || maybe_install pngquant ;;
    esac
done

ADB_PATH=""
ADB_OK=false
if ADB_PATH="$(adb_bin 2>/dev/null)"; then
    ADB_OK=true
fi
ANDROID_HOME_FOUND=""
[[ -n "$ADB_PATH" ]] && ANDROID_HOME_FOUND="$(infer_android_home "$ADB_PATH")"

PYTHON_PATH="$(tool_path python3)"
PYTHON_OK=false
[[ -n "$PYTHON_PATH" ]] && PYTHON_OK=true

CWEBP_PATH="$(tool_path cwebp)"
CWEBP_OK=false
[[ -n "$CWEBP_PATH" ]] && CWEBP_OK=true

PNGQUANT_PATH="$(tool_path pngquant)"
PNGQUANT_OK=false
[[ -n "$PNGQUANT_PATH" ]] && PNGQUANT_OK=true

DEVICES=""
DEVICE_COUNT=0
SELECTED_SERIAL="${DROIDLENS_SERIAL:-}"
DEVICE_OK=false
if [[ "$ADB_OK" == true ]]; then
    DEVICES="$(authorized_devices || true)"
    DEVICE_COUNT="$(printf '%s\n' "$DEVICES" | sed '/^$/d' | wc -l | tr -d ' ')"
    if [[ -n "$SELECTED_SERIAL" ]]; then
        if printf '%s\n' "$DEVICES" | grep -Fxq "$SELECTED_SERIAL"; then
            DEVICE_OK=true
        fi
    elif [[ "$DEVICE_COUNT" -eq 1 ]]; then
        SELECTED_SERIAL="$(printf '%s\n' "$DEVICES" | sed '/^$/d' | head -1)"
        DEVICE_OK=true
    fi
fi

STAYON_APPLIED=false
if [[ "$DEVICE_OK" == true ]]; then
    if ensure_device_stayon; then
        [[ "${DROIDLENS_STAYON_APPLIED:-0}" == "1" ]] && STAYON_APPLIED=true
    fi
fi

APP_JSON=""
APP_OK=false
if [[ "$ADB_OK" == true ]]; then
    if APP_JSON="$("$HERE/app.sh" resolve --app "${DROIDLENS_APP:-auto}" --json 2>/dev/null)"; then
        APP_OK=true
    fi
fi

write_env_file "$ADB_PATH" "$SELECTED_SERIAL" "$ANDROID_HOME_FOUND"

READY=false
[[ "$ADB_OK" == true && "$PYTHON_OK" == true && "$DEVICE_OK" == true && "$CWEBP_OK" == true ]] && READY=true

if [[ "$JSON" == "1" ]]; then
    py - "$READY" "$ROOT" "$ENV_FILE" "$ADB_OK" "$ADB_PATH" "$ANDROID_HOME_FOUND" \
        "$PYTHON_OK" "$PYTHON_PATH" "$CWEBP_OK" "$CWEBP_PATH" "$PNGQUANT_OK" "$PNGQUANT_PATH" \
        "$DEVICE_OK" "$DEVICE_COUNT" "$SELECTED_SERIAL" "$STAYON_APPLIED" "$APP_OK" "$APP_JSON" <<'PY'
import json
import sys

(
    ready,
    root,
    env_file,
    adb_ok,
    adb_path,
    android_home,
    python_ok,
    python_path,
    cwebp_ok,
    cwebp_path,
    pngquant_ok,
    pngquant_path,
    device_ok,
    device_count,
    selected_serial,
    stayon_applied,
    app_ok,
    app_json,
) = sys.argv[1:19]
try:
    app = json.loads(app_json) if app_json else None
except Exception:
    app = None
print(json.dumps({
    "ready": ready == "true",
    "root": root,
    "envFile": env_file,
    "adb": {"ok": adb_ok == "true", "path": adb_path, "androidHome": android_home},
    "python3": {"ok": python_ok == "true", "path": python_path},
    "imageTools": {
        "cwebp": {"ok": cwebp_ok == "true", "path": cwebp_path, "requiredForDefaultThumb": True},
        "pngquant": {"ok": pngquant_ok == "true", "path": pngquant_path, "required": False},
    },
    "device": {
        "ok": device_ok == "true",
        "authorizedCount": int(device_count or 0),
        "selectedSerial": selected_serial,
        "stayAwakeApplied": stayon_applied == "true",
    },
    "app": {"ok": app_ok == "true", "resolved": app},
}, ensure_ascii=False, indent=2))
PY
    [[ "$READY" == true ]] && exit 0 || exit 1
fi

echo "── droidlens doctor ───────────────────────────────"
printf 'project: %s\n' "$ROOT"
[[ "$ENSURE" == "1" ]] && printf 'env:     %s\n' "$ENV_FILE"
echo
printf '%s adb      %s\n' "$([[ "$ADB_OK" == true ]] && echo "✓" || echo "✗")" "${ADB_PATH:-not found}"
printf '%s python3  %s\n' "$([[ "$PYTHON_OK" == true ]] && echo "✓" || echo "✗")" "${PYTHON_PATH:-not found}"
printf '%s cwebp    %s\n' "$([[ "$CWEBP_OK" == true ]] && echo "✓" || echo "✗")" "${CWEBP_PATH:-not found}"
printf '%s pngquant %s\n' "$([[ "$PNGQUANT_OK" == true ]] && echo "✓" || echo "○")" "${PNGQUANT_PATH:-optional, not found}"
printf '%s device   count=%s selected=%s\n' "$([[ "$DEVICE_OK" == true ]] && echo "✓" || echo "✗")" "$DEVICE_COUNT" "${SELECTED_SERIAL:-}"
printf '%s app      %s\n' "$([[ "$APP_OK" == true ]] && echo "✓" || echo "○")" "$([[ "$APP_OK" == true ]] && echo "resolved" || echo "not resolved")"
echo
if [[ "$READY" == true ]]; then
    echo "ready=true"
    exit 0
fi
echo "ready=false"
[[ "$ADB_OK" != true ]] && install_hint adb | sed 's/^/  /'
[[ "$CWEBP_OK" != true ]] && install_hint cwebp | sed 's/^/  /'
[[ "$PYTHON_OK" != true ]] && install_hint python3 | sed 's/^/  /'
exit 1
